version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/db
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_DB: ${MONGO_DB}
    ports:
      - 27017:27017

  influx:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - ./data:/data/db
    ports:
      - '8086:8086'
    
