version: '3.1'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./docker-data/db-data:/data/db
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_DB: ${MONGO_DB}
    ports:
      - 27017:27017
