version: '3.1'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./docker-data/db-data:/data/db
    environment:
      POSTGRES_PASSWORD: ${MONGO_PASSWORD}
      POSTGRES_USER: ${MONGO_USER}
      POSTGRES_DB: ${MONGO_DB}
    ports:
      - 27017:27017
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080
