version: "3"
services:
  server:
    build: .
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - "db"
    links:
      - db
    environment:
      WAIT_HOSTS: db:8086

  db:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - ./data:/data/db
    ports:
      - "8086:8086"
