version: '3'
services:
  broker:
    build: .
    restart: always
    volumes:
      - .:/usr/brk/
      - /usr/brk/node_modules
    ports:
      - '24071:3001'
      - '24074:3002'
      - '24075:3003'
    depends_on:
      - 'influx'
    links:
      - influx
    environment:
      WAIT_HOSTS: influx:8086

  influx:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - ./data:/data/db
    ports:
      - '8086:8086'
