version: '3'
services:
  influx:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - ./data:/data/db
    ports:
      - '8086:8086'

  broker:
    build: .
    restart: always
    volumes:
      - .:/usr/brk/
      - /usr/brk/node_modules
    ports:
#       const API_PORT = 3002;
#       const BROKER_PORT = 3001;
#       const PROTO_BROKER_PORT = 3003;
      - '1883:3001' 
      - '24074:3002'
      - '24075:3003'
    depends_on:
      - 'influx'
    links:
      - influx
    environment:
      WAIT_HOSTS: influx:8086

  # Define a Telegraf service
  telegraf:
    restart: always
    image: telegraf
    links:
      - influx
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define a Chronograf service
  chronograf:
    image: chronograf
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8080:8888"
    links:
      - influx
  # Define a Kapacitor service
  kapacitor:
    image: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influx:8086
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor
    links:
      - influx
    ports:
      - "9092:9092"


