version: '3'
services:
  broker:
    build: .
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '1883:3001'
    depends_on:
      - 'influx'
    links:
      - influx
    environment:
      WAIT_HOSTS: influx:8086

  influx:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - ./data:/data/db
    ports:
      - '8086:8086'
